### ISSUE TITLE
google 

### ISSUE THREAD

**Issue by Loopemailsecured2381** [heschy/Stargate-Generator#1]
Get my old emails back 6 months ago. 
And change my phone number on m1 #6613469974 old 
New 6618622408

**Comment by heschy** [comment]
To help me improving this Site, might you please add a [Label ](https://github.com/heschy/Stargate-Generator/labels)to your Issue?

**Comment by Loopemailsecured2381** [comment]
Your work for google name it same old thing for privacy, breach of contract
frozey actt
 I told Harold at M1 that my fb was hacked and number was stolen and still
being used on m1 which might be a way to be in.. I have prints outs of all
mail.

**Comment by heschy** [comment]
I do not understand what you mean. I do not know why you are saying something about Google and I do not know who you are. I do not speak english, so please write clearly. And say what you want. And who is Harold?

**Comment by Loopemailsecured2381** [comment]
Thank you for your response.
